- include: RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: Debian.yml
  when: ansible_os_family == 'Debian'

- name: be sure client.json is copied
  template:
    src: client.j2
    dest: "/etc/sensu/conf.d/client.json"
  notify:
    - restart sensu-client

- name: be sure rabbitmq.json is copied
  template:
    src: rabbitmq.j2
    dest: "/etc/sensu/conf.d/rabbitmq.json"
  notify:
    - restart sensu-client

- name: be sure sensu-client is running and enabled
  service:
    name: sensu-client
    state: started
    enabled: yes

- name: be sure sensu-plugins-{{ item }} is cloned
  git:
    repo: "{{ sensu_client_github_url_base }}{{ item }}.git"
    dest: /tmp/sensu-plugins-{{ item }}
    update: yes
  with_items:
     - cpu-checks
     - disk-checks
     - http
     - memory-checks
     - ntp

- name: be sure check-{{ item.checkname }}.rb is copied
  copy:
    src: /tmp/sensu-plugins-{{ item.reponame }}/bin/check-{{ item.checkname }}.rb
    dest: /etc/sensu/plugins/check-{{ item.checkname }}.rb
    remote_src: true
    owner: sensu
    group: sensu
    mode: 0500
  with_items:
    - { reponame: 'cpu-checks', checkname: 'cpu' }
    - { reponame: 'disk-checks', checkname: 'disk-usage' }
    - { reponame: 'http', checkname: 'http' }
    - { reponame: 'memory-checks', checkname: 'memory-percent' }
    - { reponame: 'memory-checks', checkname: 'swap-percent' }
    - { reponame: 'ntp', checkname: 'ntp' }
  notify: restart sensu-client

- name: be sure checks.json is copied
  template:
    src: checks.j2
    dest: "/etc/sensu/conf.d/checks.json"
  notify: restart sensu-client
