- include: RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: Debian.yml
  when: ansible_os_family == 'Debian'

- name: be sure {{ item }}.json is copied
  template:
    src: "{{ item }}.j2"
    dest: "/etc/sensu/conf.d/{{ item }}.json"
  notify:
    - restart sensu-client
  with_items:
    - checks
    - client
    - rabbitmq

- name: be sure sensu-client is running and enabled
  service:
    name: sensu-client
    state: started
    enabled: yes

- name: get installed sensu-plugins
  command: "{{ sensu_client_gem }} list --local"
  register: installed_plugins
  changed_when: false

- name: be sure sensu-plugins-{{ item.name }} is installed
  command: sensu-install -p {{ item.name }}:{{ item.version }}
  when: "'sensu-plugins-{{ item.name }} ({{ item.version }})' not in installed_plugins.stdout"
  with_items: "{{ sensu_client_plugins }}"

- name: be sure sys-filesystem gem is installed
  gem:
    name: sys-filesystem
    state: latest
    user_install: no
    executable: "{{ sensu_client_gem }}"
