- name: be sure client.json is copied
  template:
    src: client.j2
    dest: "/etc/sensu/conf.d/client.json"
  notify:
    - restart sensu-client

- name: be sure rabbitmq.json is copied
  template:
    src: rabbitmq.j2
    dest: "/etc/sensu/conf.d/rabbitmq.json"
  notify:
    - restart sensu-client

- name: be sure sensu-client is running and enabled
  service:
    name: sensu-client
    state: started
    enabled: yes

- name: be sure sensu-plugins-{{ item }} is cloned
  git:
    repo: {{ sensu_client_github_url_base }}{{ item }}.git
    dest: /tmp/sensu-plugins-{{ item }}
    update: yes
  with_items:
     - cpu-checks
     - http

- name: be sure check-{{ checkname }}.rb is copied
  copy:
    src: /tmp/sensu-plugins-{{ reponame }}/bin/check-{{ checkname }}.rb
    dest: /etc/sensu/plugins/check-{{ checkname }}.rb
    remote_src: true
    owner: sensu
    group: sensu
    mode: 0500
  with_items:
    - { reponame: 'cpu-checks', checkname: 'cpu' }
    - { reponame: 'http', checkname: 'http' }
  notify: restart sensu-client

- name: be sure checks.json is copied
  template:
    src: checks.j2
    dest: "/etc/sensu/conf.d/checks.json"
  notify: restart sensu-client
