- include: RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: Debian.yml
  when: ansible_os_family == 'Debian'

- name: be sure client.json is copied
  template:
    src: client.j2
    dest: "/etc/sensu/conf.d/client.json"
  notify:
    - restart sensu-client

- name: be sure rabbitmq.json is copied
  template:
    src: rabbitmq.j2
    dest: "/etc/sensu/conf.d/rabbitmq.json"
  notify:
    - restart sensu-client

- name: be sure sensu-client is running and enabled
  service:
    name: sensu-client
    state: started
    enabled: yes

- name: get installed sensu-plugins
  command: /opt/sensu/embedded/bin/gem list --local
  register: installed_plugins
  changed_when: false

- name: be sure sensu-plugins-{{ item }} is installed
  command: sensu-install -p {{ item }}
  when: "'^sensu-plugins-{{ item }}\s' not in installed_plugins.stdout"
  with_items: "{{ plugins }}"

- name: be sure checks.json is copied
  template:
    src: checks.j2
    dest: "/etc/sensu/conf.d/checks.json"
  notify: restart sensu-client

- name: be sure sys-filesystem gem is installed
  gem:
    name: sys-filesystem
    state: latest
    user_install: no
    executable: /opt/sensu/embedded/bin/gem
