- name: be sure {{ item }} is installed
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - ntp
    - ruby-devel

- name: install the 'Development tools' package group
  yum: name="@Development tools" state=present
